# Generated by Django 5.0.2 on 2024-03-01 09:53

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="roles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[("ADMIN", "ADMIN"), ("CUSTOMER", "CUSTOMER")],
                    max_length=20,
                ),
                default="CUSTOMER",
                size=6,
            ),
        ),
    ]
