default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
      files: |
        (?x)^(
          example/.*
          |static/.*
          |templates/.*
        )$
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.12.1
    hooks:
      - id: black
        args: ['--exclude=..venv', '--skip-string-normalization']

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==23.10.0

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==23.9.16
          - flake8-no-pep420==2.7.0

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py312-plus]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.15.0
    hooks:
      - id: django-upgrade
        args: [--target-version, '5.0']

#   - repo: https://github.com/asottile/reorder-python-imports
#     rev: v3.12.0
#     hooks:
#       - id: reorder-python-imports
#         args:
#           - --py312-plus

  - repo: https://github.com/rtts/djhtml
    rev: 3.0.6
    hooks:
      - id: djhtml
        args:
          - --tabwidth=2

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck

#  - repo: local
#    hooks:
#      - id: check-fixture-types
#        name: Check fixture types
#        language: fail
#        entry: Please convert non-YAML fixtures to YAML.
#        files: /fixtures/
#        exclude_types: [yaml]

#   - repo: local
#     hooks:
#       - id: fix-django-links
#         name: Fix Django links
#         language: script
#         entry: scripts/fix_django_links.py
#         types_or:
#           - markdown
#           - python
#           - rst
