extend-exclude = ["src/apps/*/migrations/*", "static", "staticfilles", "templates"]
include = ["src/**/*.py", "scripts/**/*.py", "tests/**/*.py"]
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "venv",
  "*/migrations/*.py",
  "staticfiles/*"
]
line-length = 88
indent-width = 4
target-version = "py312"
fix = true

[lint]
preview = true
select = [
  "F",     # Pyflakes
  "E",     # pycodestyle errors
  "W",     # pycodestyle warnings
  "C90",   # mccabe
  "I",     # isort
  "N",     # pep8-naming
  "UP",    # pyupgrade
  "PL",    # pylint
  "PERF",  # perflint
  "BLE",
  "S",     # flake8-bandit
  "FBT",   # flake8-boolean-trap
  "B",     # flake8-bugbear
  "DJ",    # flake8-django
  "ICN",   # flake8-import-conventions
  "ASYNC", # flake8-async
  "C4",    # flake8-comprehensions
  "Q",     # flake8-quotes
  "RET",   # flake8-return
  "SIM",   # flake8-simplify
  "TID",   # flake8-tidy-imports
  "TCH",   # flake8-type-checking
  "PTH",   # flake8-use-pathlib
  "INT",   # flake8-gettext
  "SLOT",  # flake8-slots
  "SLF",   # flake8-self
  "RSE",   # flake8-raise
  "PYI",   # flake8-pyi"
  "PIE",   # flake8-pie"
  "ISC",   # flake8-implicit-str-concat
  "A",     # flake8-builtins
  "COM",   # flake8-commas
  "T10",   # flake8-debugger
  "YTT",   # flake8-2020
  "G",     # flake8-logging-format
  "ERA",   # eradicate
  "RUF",   # ruff
  "FLY",   # flynt
  "FURB",  # refurb
]
ignore = [
  "S101",
  "RUF012",
  "SIM102",
  "PLR6301",
  "ERA001",
  "S105",
  "PLR6201",
]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.isort]
force-single-line = true

#[lint.pydocstyle]
#convention = "google"

[format]
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
#preview = true
#exclude = ["*.pyi"]
#quote-style = "single"
#docstring-code-format = true

[lint.flake8-quotes]
inline-quotes = "single"

[lint.pylint]
max-locals = 20
max-public-methods = 30
