# Generated by Django 5.0.2 on 2024-02-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pendinguser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
